source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "6.1"


pod 'Reachability', '~> 3.1.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'PXAlertView', '~> 0.1.0'
pod 'hpple', '~> 0.2.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'ZBarSDK', '~> 1.3.1'
pod 'AFNetworking/NSURLConnection', '~> 2.3.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'Base64', '~> 1.0.1'
pod 'FastAnimationWithPOP', '~> 0.0.2'



target :KECallsAttributionTests, :exclusive => true do
  # pod 'Kiwi'
end
